version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - '${VOLUME_PATH}/elasticsearch:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'