version: '3.3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '${VOLUME_PATH}/gitlabgitlab/config:/etc/gitlab'
      - '${VOLUME_PATH}/gitlab/gitlab/logs:/var/log/gitlab'
      - '${VOLUME_PATH}/gitlab/gitlab/data:/var/opt/gitlab'